name: Calculate test coverage

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
        cache: 'pip'
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -e .
        pip install pytest pytest-cov pytest-unordered
    - name: Run tests
      run: |-
        pytest --cov=nx2vos --cov-report xml:coverage.xml --cov-report term
    - name: Upload coverage report
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.xml
